function ageGroup(age){
    if(age<0)
        console.log(`${age}: возраст не может быть отрицательным`)
    else if(age<3)
        console.log(`${age}: младенец`)
    else if(age<14)
        console.log(`${age}: ребенок`)
    else if(age<20)
        console.log(`${age}: подросток`)
    else if(age<66)
        console.log(`${age}: взрослый`)
    else if(age>65)
        console.log(`${age}: пожилой`)
    else console.log(`${age}: на вход подано не число`)
}

ageGroup(-1)
ageGroup(0)
ageGroup(2)
ageGroup(3)
ageGroup(13)
ageGroup(14)
ageGroup(19)
ageGroup(20)
ageGroup(65)
ageGroup(66)
ageGroup("один")